version: "3.9"

x-api-env: &api_env
  ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
  SECRET_KEY: ${SECRET_KEY}
  ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASS}
      POSTGRES_DB: ${PGDB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${PGPORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    profiles: ["testing","prod"]

  api:
    build: .
    restart: unless-stopped
    env_file: ${ENV_FILE:?set ENV_FILE}
    environment:
      <<: *api_env
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_started
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000
    profiles: ["testing","prod"]

  # Optional TLS reverse proxy for prod
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    profiles: ["prod"]

volumes:
  db_data:
  caddy_data:
  caddy_config:
